const run = () => {
  throw new Error('wow')
}
run()